version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage  # Persistent volume for Qdrant
    restart: always

  database:
    build: ./database_module
    container_name: database_service
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=news_articles
    depends_on:
      - qdrant
    restart: always

volumes:
  qdrant_data:  # Define the persistent volume
    name: qdrant_data
