log_level: INFO
service:
  http_port: 6333
  grpc_port: 6334
storage:
  path: "/qdrant/storage"
optimizers:
  indexing_threshold: 20000
  flush_interval_sec: 30
  max_segment_size: 10000000
  memmap_threshold: 10000
  indexing_memory: 1024
